
version: 0.2

env:
  variables:
    STAGING_FUNCTION_NAME: "samp-app-2023-09-17-1453-staging"
    STAGING_URL: "https://bnqxdygf7nnx7mbdtmgmq2xl3y0kefch.lambda-url.us-east-2.on.aws/"
    PRODUCTION_FUNCTION_NAME: "samp-app-2023-09-17-1453-production"
    PRODUCTION_URL: "https://ax6kykhpw3csjn3ulefkultfvy0ztcts.lambda-url.us-east-2.on.aws/"

phases:
  install:
    commands:
      - python3 -m venv local
      - . ./local/bin/activate
      - make requirements

  pre_build:
    commands:
      - . ./local/bin/activate
      - make check lint
      - make test

  build:
    commands:
      - make build

  post_build:
    commands:
      - make deploy PLATFORM="AWS CodeBuild" FUNCTION=$STAGING_FUNCTION_NAME VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - 'lambda.zip'
